"""
tables.py: LaTeX tables for the manuscript, generated from the confirmatory
result tables so that no number is typed by hand.

Output: results/tables/table_rules.tex   the quantified rule table (group tier,
                                       every rule powered in at least one
                                       collection), a longtable
        results/tables/table_summary.tex  counts of rules per LR+ band and per
                                       spectral region, both collections
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
OUT = ROOT / "results" / "tables"
PRIMARY_PROM = 0.02
FINGERPRINT_MAX = 1350.0
DIAGNOSTIC_MIN = 1500.0

GROUP_NAMES = {
    "methyl": "methyl", "methylene": "methylene", "methylene_chain_4": "(CH$_2$)$_{n\\geq4}$ chain",
    "aromatic_mono": "benzene, monosubstituted", "aromatic_ortho": "benzene, ortho",
    "aromatic_meta": "benzene, meta", "aromatic_para": "benzene, para",
    "alcohols": "alcohol", "alcohol_primary": "primary alcohol", "alcohol_secondary": "secondary alcohol",
    "alcohol_tertiary": "tertiary alcohol", "phenol": "phenol",
    "ether_saturated": "saturated ether", "ether_mixed": "aryl alkyl ether", "ether_aryl": "diaryl ether",
    "ketone_saturated": "saturated ketone", "ketone_aromatic": "aromatic ketone",
    "carboxylic_acid_saturated": "saturated carboxylic acid", "carboxylic_acid_aromatic": "aromatic carboxylic acid",
    "carboxylic_acids": "carboxylic acid",
    "ester_saturated": "saturated ester", "ester_aromatic": "aromatic ester", "carbonate_organic": "organic carbonate",
    "amides": "amide", "amide_primary": "primary amide", "amide_secondary": "secondary amide",
    "amine_primary": "primary amine", "amine_primary_saturated": "primary alkyl amine",
    "amine_primary_aromatic": "primary aryl amine", "amine_secondary": "secondary amine",
    "amine_secondary_saturated": "secondary alkyl amine", "amine_secondary_aromatic": "secondary aryl amine",
    "aldehydes": "aldehyde", "aldehyde_saturated": "saturated aldehyde", "aldehyde_aromatic": "aromatic aldehyde",
    "alkene_vinyl": "vinyl alkene", "alkene_trisubstituted": "trisubstituted alkene",
    "alkyne_terminal": "terminal alkyne", "alkyne_internal": "internal alkyne",
    "nitrile_saturated": "saturated nitrile", "nitrile_aromatic": "aromatic nitrile", "nitro": "nitro",
}


def tex(s: str) -> str:
    return (s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
             .replace("#", "\\#").replace("=", "$=$"))


def fmt_lr(v: float, under: bool) -> str:
    if pd.isna(v):
        return "--"
    s = f"{v:.1f}" if v < 10 else f"{v:.0f}"
    return f"({s})" if under else s


def fmt_lr2(v: float, under: bool) -> str:
    if pd.isna(v):
        return "--"
    s = f"{v:.2f}"
    return f"({s})" if under else s


def rule_table(rules: pd.DataFrame, comp: pd.DataFrame) -> str:
    r = rules.set_index("rule_id")
    d = comp[(comp.tier == "group") & ~(comp.chem_underpowered & comp.nist_underpowered)].copy()
    d["group_name"] = d.truth_group.map(GROUP_NAMES).fillna(d.truth_group)
    d = d.sort_values(["wn_min"], ascending=False)
    lines = [
        "% generated by scripts/tables.py, do not edit by hand",
        "\\begingroup\\footnotesize\\setlength{\\tabcolsep}{4pt}\n\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{2.5cm}>{\\raggedright\\arraybackslash}p{6.6cm}rrrrrrrr@{}}",
        "\\caption{Diagnostic value of the frozen correlation rules (group tier) in the two collections. "
        "Window, stated intensity and description as transcribed from the source; $n_+$, number of spectra containing "
        "the group; LR$^+$ and LR$^-$ at the primary threshold with the full rule definition. "
        "Values in parentheses are underpowered (fewer than 10 positives) and are shown for completeness only.}"
        "\\label{tab:rules}\\\\",
        "\\toprule",
        " & & & \\multicolumn{3}{c}{Chemotion (ATR)} & & \\multicolumn{3}{c}{NIST WebBook} \\\\",
        "\\cmidrule(lr){4-6}\\cmidrule(lr){8-10}",
        "Group & Band (cm$^{-1}$, intensity) & & $n_+$ & LR$^+$ & LR$^-$ & & $n_+$ & LR$^+$ & LR$^-$ \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\toprule",
        " & & & \\multicolumn{3}{c}{Chemotion (ATR)} & & \\multicolumn{3}{c}{NIST WebBook} \\\\",
        "\\cmidrule(lr){4-6}\\cmidrule(lr){8-10}",
        "Group & Band (cm$^{-1}$, intensity) & & $n_+$ & LR$^+$ & LR$^-$ & & $n_+$ & LR$^+$ & LR$^-$ \\\\",
        "\\midrule",
        "\\endhead",
        "\\midrule\\multicolumn{10}{r}{\\small continued on the next page}\\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]
    for _, x in d.iterrows():
        rr = r.loc[x.rule_id]
        inten = "" if rr.intensity == "any" or pd.isna(rr.intensity) else f", {rr.intensity}"
        shape = "" if rr["shape"] == "any" or pd.isna(rr["shape"]) else f", {rr['shape']}"
        extra = ""
        if not pd.isna(rr.requires_wn_min):
            extra += f" + band {int(rr.requires_wn_min)}--{int(rr.requires_wn_max)}"
        if not pd.isna(rr.forbids_wn_min):
            extra += f", no band {int(rr.forbids_wn_min)}--{int(rr.forbids_wn_max)}"
        band = f"{int(x.wn_min)}--{int(x.wn_max)}{inten}{shape}{extra}"
        desc = tex(str(rr.description))
        lines.append(
            f"{tex(x.group_name)} & {band}; {{\\scriptsize {desc}}} & "
            f"& {int(x.chem_n_pos)} & {fmt_lr(x.chem_LR_pos, x.chem_underpowered)} & {fmt_lr2(x.chem_LR_neg, x.chem_underpowered)} & "
            f"& {int(x.nist_n_pos)} & {fmt_lr(x.nist_LR_pos, x.nist_underpowered)} & {fmt_lr2(x.nist_LR_neg, x.nist_underpowered)} \\\\"
        )
    lines.append("\\end{longtable}\\endgroup")
    return "\n".join(lines) + "\n"


def summary_table(mchem: pd.DataFrame, mnist: pd.DataFrame) -> str:
    def counts(m):
        p = m[(m.prominence == PRIMARY_PROM) & (m.definition == "+shape") & (m.stratum == "main")
              & (m.tier == "group") & (~m.underpowered)]
        fp = p[p.wn_max <= FINGERPRINT_MAX]
        hi = p[p.wn_min >= DIAGNOSTIC_MIN]
        mid = p[(p.wn_max > FINGERPRINT_MAX) & (p.wn_min < DIAGNOSTIC_MIN)]
        def band(s):
            return [int((s.LR_pos >= 5).sum()), int(((s.LR_pos >= 2) & (s.LR_pos < 5)).sum()),
                    int(((s.LR_pos >= 1.2) & (s.LR_pos < 2)).sum()), int((s.LR_pos < 1.2).sum()), len(s), s.LR_pos.median()]
        return {"all": band(p), "hi": band(hi), "mid": band(mid), "fp": band(fp)}
    c, n = counts(mchem), counts(mnist)
    rows = [("All powered rules", "all"), ("Window at or above 1500 cm$^{-1}$", "hi"),
            ("Window straddling 1350--1500 cm$^{-1}$", "mid"), ("Window at or below 1350 cm$^{-1}$ (fingerprint)", "fp")]
    lines = [
        "% generated by scripts/tables.py, do not edit by hand",
        "\\begin{table}[t]\\centering\\small",
        "\\caption{Number of powered rules in each LR$^+$ band, by spectral region. "
        "LR$^+ \\geq 5$ is the usual threshold for a test that changes a decision on its own; "
        "LR$^+ < 1.2$ means the band is present about as often without the group as with it.}\\label{tab:summary}",
        "\\begin{tabular}{@{}lrrrrrr@{}}\\toprule",
        "Region & $\\geq 5$ & 2 to 5 & 1.2 to 2 & $<1.2$ & rules & median LR$^+$ \\\\",
    ]
    for title, key in rows:
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\emph{{{title}}}}} \\\\")
        for lab, src in (("Chemotion", c), ("NIST", n)):
            b = src[key]
            lines.append(f"\\quad {lab} & {b[0]} & {b[1]} & {b[2]} & {b[3]} & {b[4]} & {b[5]:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rules = pd.read_csv(ROOT / "rules" / "rules_frozen.csv")
    comp = pd.read_csv(PROCESSED / "rule_metrics_comparison.csv")
    mchem = pd.read_csv(PROCESSED / "rule_metrics_confirm.csv")
    mnist = pd.read_csv(PROCESSED / "rule_metrics_nist_confirm.csv")
    (OUT / "table_rules.tex").write_text(rule_table(rules, comp), encoding="utf-8")
    (OUT / "table_summary.tex").write_text(summary_table(mchem, mnist), encoding="utf-8")
    print("[tables] wrote table_rules.tex and table_summary.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
